// Generated by scripts/generate-registry.mjs — do not edit by hand.
// Add an app with `npm run new:app <slug>` or by creating src/apps/<slug>/meta.ts next to its cover and icon.
import type { AppMeta } from "./types";

import meta0 from "./hum/meta";

export const metas: { slug: string; meta: AppMeta }[] = [
  { slug: "hum", meta: meta0 },
];
