// Generated by scripts/generate-registry.mjs — do not edit by hand.
// Add a design with `npm run new:design <slug>` or by creating src/designs/<slug>/meta.ts next to its image.
import type { DesignMeta } from "./types";

import meta0 from "./analytics-dashboard/meta";
import meta1 from "./now-playing/meta";
import meta2 from "./wallet-home/meta";

export const metas: { slug: string; meta: DesignMeta }[] = [
  { slug: "analytics-dashboard", meta: meta0 },
  { slug: "now-playing", meta: meta1 },
  { slug: "wallet-home", meta: meta2 },
];
