// Generated by scripts/generate-registry.mjs — do not edit by hand.
// Add a craft with `npm run new <slug>` or by creating src/crafts/<slug>/{meta.ts,craft.tsx}.
import type { CraftMeta } from "./types";

import meta0 from "./dynamic-island/meta";
import meta1 from "./hold-to-confirm/meta";
import meta2 from "./magnetic-button/meta";
import meta3 from "./number-ticker/meta";
import meta4 from "./segmented-control/meta";
import meta5 from "./spring-toggle/meta";
import meta6 from "./text-scramble/meta";

export const metas: { slug: string; meta: CraftMeta }[] = [
  { slug: "dynamic-island", meta: meta0 },
  { slug: "hold-to-confirm", meta: meta1 },
  { slug: "magnetic-button", meta: meta2 },
  { slug: "number-ticker", meta: meta3 },
  { slug: "segmented-control", meta: meta4 },
  { slug: "spring-toggle", meta: meta5 },
  { slug: "text-scramble", meta: meta6 },
];
