// Generated by scripts/generate-registry.mjs — do not edit by hand.
// Add a craft with `npm run new <slug>` or by creating src/crafts/<slug>/{meta.ts,craft.tsx}.
import type { CraftComponent } from "./types";

import Craft0 from "./activity-rings/craft";
import Craft1 from "./dynamic-island/craft";
import Craft2 from "./emoji-tapback/craft";
import Craft3 from "./hold-to-confirm/craft";
import Craft4 from "./magnetic-button/craft";
import Craft5 from "./number-ticker/craft";
import Craft6 from "./segmented-control/craft";
import Craft7 from "./spring-toggle/craft";
import Craft8 from "./text-scramble/craft";

export const components: Record<string, CraftComponent> = {
  "activity-rings": Craft0,
  "dynamic-island": Craft1,
  "emoji-tapback": Craft2,
  "hold-to-confirm": Craft3,
  "magnetic-button": Craft4,
  "number-ticker": Craft5,
  "segmented-control": Craft6,
  "spring-toggle": Craft7,
  "text-scramble": Craft8,
};
