// Generated by scripts/generate-registry.mjs — do not edit by hand.
// Add a craft with `npm run new <slug>` or by creating src/crafts/<slug>/{meta.ts,craft.tsx}.
import type { CraftComponent } from "./types";

import Craft0 from "./dynamic-island/craft";
import Craft1 from "./hold-to-confirm/craft";
import Craft2 from "./magnetic-button/craft";
import Craft3 from "./number-ticker/craft";
import Craft4 from "./segmented-control/craft";
import Craft5 from "./spring-toggle/craft";
import Craft6 from "./text-scramble/craft";

export const components: Record<string, CraftComponent> = {
  "dynamic-island": Craft0,
  "hold-to-confirm": Craft1,
  "magnetic-button": Craft2,
  "number-ticker": Craft3,
  "segmented-control": Craft4,
  "spring-toggle": Craft5,
  "text-scramble": Craft6,
};
